### ISSUE TITLE
Does this kit work with the latest (3.x) version of Tailwind CSS?

### ISSUE THREAD

**Issue by fakeheal** [sailui/ui#17]
Hi,

awesome ui kit, love its simplicity, used a lot of the code as reference for building my own ui kit! Thank you! 🙏❤️ Also, please note I am very new to TailwindCSS or utility-first CSS frameworks, I am also a backend developer, so CSS in general is a PITA for me 😅.

Anyways, I created a new Tailwind CSS project as described in [their docs here](https://tailwindcss.com/docs/installation). Then I added `sailui`, as described in your README. As per my `package-lock.json`, I have the following package versions: 

| Package| Version|
| ----------- | ----------- |
| tailwindcss | 3.0.11|
| sailui | 0.6.0|
| @tailwindcss/forms| 0.4.0|

and when I run:

```
$ npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch # as described in tailwindcss docs
```

I get: 
```
UnhandledPromiseRejectionWarning: TypeError: forms.handler is not a function
```

in `@tailwindcss/forms` repository I can see there's a not stating:

> Note that @tailwindcss/forms is designed for Tailwind CSS v2.0.

**Comment by matt-daneshvar** [comment]
Hi Ivanka - Thank you so much for trying out this package and for immediately contributing!

I just merged your PR and released `v0.6.1`. I will go ahead and close this issue, but please let me know if you still encouter the same error after the update.
