### ISSUE TITLE
Consider converting Sail UI into a Tailwind plugin

### ISSUE THREAD

**Issue by matt-daneshvar** [sailui/ui#4]

**Comment by cbenz** [comment]
Hi

I started a project based on the idea of Tailwind plugins for UIs. 

https://gitlab.com/cbenz/tailwind-toolkit

It is extremely alpha, there is about nothing. 

Example with alerts : https://gitlab.com/cbenz/tailwind-toolkit/-/blob/master/plugins/alert.js

I'm happy to have found another project attempting to produce a UI toolkit based on Tailwind! I don't think that Tailwind UI has the same approach.

**Comment by matt-daneshvar** [comment]
Hi Christophe. That's pretty cool! 

I think your approach of using plugins is much better aligned with Tailwind's philosophy. I gotta explore that for this repo soon too. 

I've come across other devs building UI components on [Awesome Tailwind](https://github.com/aniftyco/awesome-tailwindcss#ui-libraries-components--templates). If you haven't yet, I think you should check them out too!
