### ISSUE TITLE
Implement a `link` component

### ISSUE THREAD

**Issue by matt-daneshvar** [sailui/ui#9]
## Syntax
```html
<a href="#" class="link"></a>
```

## Appearance
When the primary color is set to `#000`:
![image](https://user-images.githubusercontent.com/10030505/99605741-4395d380-2a43-11eb-9960-68c39e6ba1d9.png)

When the primary color is set to `#ff6394`: 
![image](https://user-images.githubusercontent.com/10030505/99606475-cec39900-2a44-11eb-848b-a9e671ee5d1b.png)

## Notes
The `link` class should:
- Follow the primary `color` available on the `theme` object for its `color` and `border-bottom` properties.
- Follow the same *hover* color as `btn` for its *hover* state. See the creation of `hover` color [here](https://github.com/sailui/ui/blob/dab674b2031758bfb0c86940c11ad9c26b175b89/src/components/btn.js#L4-L12).
- Follow the same `200ms` for its `transition-duration`.

**Comment by matteociasco** [comment]
@matt-daneshvar i would like to contribute if it is possible! 😄

**Comment by matt-daneshvar** [comment]
Hi Matteo, absolutely! Thanks for considering to take part!

I haven't had a chance to write proper contributation guidelines just yet, but please consider these few things if you're keen to contribute: 

- Please be open to the idea that your PR may not get merged OR that your code may be modified before it's merged. 
- Styling is subjective. For the time being, it will be my responsibility to judge whether a new component fits the collection. 
- If you have new ideas, please open them as new issues for discussion before commiting time to build them.

**Comment by matteociasco** [comment]
@matt-daneshvar  yup, absolutely. 

Just give me some information about this component and i'll try my best to make this work!

**Comment by matt-daneshvar** [comment]
Sure, I just added a brief to the [top of this thread](https://github.com/sailui/ui/issues/9#issue-737518957).

**Comment by matteociasco** [comment]
@matt-daneshvar okay, i'll do it.

Are you going to assign te issue to me?

Are you going to add add me as a collaborator to this organization so i can push the code directly in a branch of this repo or i need to fork it?

**Comment by matt-daneshvar** [comment]
I've assigned you to the issue. Please fork and send a PR.

**Comment by matteociasco** [comment]
@matt-daneshvar during an `npm run build` to build the output css it says `Cannot find module 'autoprefixer'`. Is there any additional configuration that i need to do to do this?

**Comment by matt-daneshvar** [comment]
Sorry @matteociasco, I just realized `tailwindcss` wasn't included as a dev dependency. Just [added it](https://github.com/sailui/ui/commit/d07e329cd7a9444364f33c403d014f34291af2ee) in and pushed it up to the `master` branch. 

If you clone the latest `master` now, you should be able to get up and running with `npm i` and `npm run build`.
